database:
  host: localhost
  port: 5432
  user: youruser
  password: yourpassword
  dbname: productdb

redis:
  host: localhost
  port: 6379

rabbitmq:
  host: localhost
  port: 5672

server:
  host: localhost
  port: 8080

aws:
  s3bucket: your-bucket-name
  region: us-west-2